AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: MyLambdaFunction
      Runtime: python3.8
      Handler: lambda_function.lambda_handler
      Code:
        ZipFile: |
          import boto3

          def lambda_handler(event, context):
              sqs = boto3.client('sqs')
              queue_url = 'YOUR_QUEUE_URL'  # Substitua pelo URL da fila do SQS desejada
              response = sqs.send_message(
                  QueueUrl=queue_url,
                  MessageBody='Hello from Lambda!'
              )
              print(response)

      Role: YOUR_LAMBDA_ROLE_ARN  # Substitua pelo ARN do papel (role) que você deseja usar para a função Lambda

  MyQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: MyQueue
